export interface TeamMember {
  id: string;
  name: string;
  position: string;
  image: string;
  bio: string;
  category: "staff" | "management" | "associates" | "partners";
}

export const TEAM_MEMBERS: TeamMember[] = [
  // PARTNERS
  {
    id: "walat-aqrawi",
    name: "Walat Aqrawi",
    position: "Founding Partner",
    image: "/images/headshots/Walat Aqrawi.webp",
    bio: "Walat Aqrawi is the Founding Partner of Aqrawi Law Firm. With decades of litigation experience, he has represented clients in high-stakes personal injury, commercial disputes, and complex litigation. He is dedicated to aggressive advocacy, unwavering integrity, and securing maximum recoveries for injury victims and their families.",
    category: "partners",
  },
  {
    id: "aaron-aiken",
    name: "Aaron Aiken",
    position: "Partner",
    image: "/images/headshots/Aaron Aiken.webp",
    bio: "Aaron Aiken is a Partner at Aqrawi & Associates and a driving force behind the firm’s continued success. Known for his dedication, experience, and tireless work ethic, Mr. Aiken plays a leading role across a wide range of cases, delivering strategic insight and consistent results.\n\nSince the early days of the firm, Mr. Aiken has been instrumental in its growth and evolution, helping shape the high standard of excellence that defines Aqrawi & Associates today. His leadership, reliability, and sharp legal judgment have made him a trusted advocate for clients and a cornerstone of the firm.\n\nOriginally from Indiana, Mr. Aiken earned his undergraduate degree from Indiana University and his Juris Doctor from Thurgood Marshall School of Law. From the outset of his legal career, he has remained committed to representing clients with integrity and professionalism.\n\nRespected for his hands-on approach and attention to detail, Mr. Aiken is deeply involved in every case he handles.",
    category: "partners",
  },

  // MANAGEMENT
  {
    id: "mohammed-khallaf",
    name: "Mohammed Khallaf",
    position: "General Manager",
    image: "/images/headshots/headshot mohammed.png",
    bio: "Mohammed Khallaf serves as the General Manager of Aqrawi & Associates Law Firm, PLLC, where he has been a valued member of the team since June 2017. Since joining the firm, Mohammed has grown alongside the organization, beginning in legal support and advancing into a leadership role overseeing operations across the firm’s Houston, Laredo, San Antonio, and international offices.\n\nOriginally from Jeddah, Saudi Arabia, Mohammed moved to the United States in 2013 and built his education and professional career in Texas. He earned his Bachelor of Arts from the University of Houston in Political Science and Public Relations and later earned his Juris Doctor from Texas Southern University’s Thurgood Marshall School of Law. He also holds a Mediation Certification, a Global Studies and Research certification from the University of Houston Honors College, and completed coursework and received a certificate from the Institut Catholique de Paris, also known as the Catholic University of Paris, in Paris, France.\n\nMohammed’s experience shaped by his background in government, diplomacy, international affairs, consular matters, civic participation, political campaigns, and community leadership has strengthened his ability to communicate effectively, understand people from different backgrounds, and approach legal matters with strategy and professionalism. This experience benefits clients by helping him navigate sensitive issues, support strong communication, and assist in resolving matters efficiently.\n\nAs General Manager, Mohammed oversees the firm’s day-to-day operations, staff development, training, client relations, and case support systems. His work includes assisting with case management, negotiations, legal research, investigation, document coordination, medical records coordination, and pre-litigation and litigation support. He also helps support the firm’s work across personal injury, immigration, criminal, family, and international consular matters.\n\nMohammed understands that negotiation and conflict resolution are key factors in achieving successful case outcomes. He works to help move cases forward with clarity, organization, and practical problem-solving while ensuring that clients feel heard, informed, and supported throughout the process.\n\nFluent in English and Arabic, Mohammed is able to connect with clients from diverse backgrounds and communities. Outside of work, he enjoys music and DJing, soccer, horseback riding, fitness, martial arts, and boxing. He also maintains a strong interest in diplomacy, international law, human rights, business, politics, and global affairs.",
    category: "management",
  },
  {
    id: "monica-toscano",
    name: "Monica Toscano",
    position: "Assistant Manager",
    image: "/images/headshots/monica headshot.png",
    bio: "Monica Toscano serves as Assistant Manager at Aqrawi & Associates, where she brings more than 15 years of experience in administration, client service, records management, and operational support. As a bilingual professional fluent in English and Spanish, Monica is dedicated to helping clients feel informed, supported, and confident throughout every stage of their legal matter.\n\nBorn in McAllen, Texas, and raised in Houston, Monica comes from a humble background that taught her the value of hard work, perseverance, and integrity. Before entering the legal field, she held leadership and administrative roles in public health, healthcare administration, banking, and insurance, gaining valuable experience in client relations, compliance, operations management, and problem-solving.",
    category: "management",
  },
  {
    id: "mahmood-noaman",
    name: "Mahmood Noaman",
    position: "Iraq Branch Manager / Marketing",
    image: "/images/headshots/Photo headshot 1.png",
    bio: "Mahmood Noaman serves as the Iraq Branch Manager / Marketing at Aqrawi & Associates, overseeing our operations and marketing directions in the region. He leads regional client communication and coordinates international business development.",
    category: "management",
  },

  // ASSOCIATES
  {
    id: "jerry-von-sternberg",
    name: "Jerry C. von Sternberg",
    position: "Attorney at Law",
    image: "/images/headshots/jerry headshot.png",
    bio: "Jerry C. von Sternberg is an experienced litigation attorney and graduate of the University of Texas at Austin School of Law. Throughout his career, he has represented clients from both plaintiff and insurance defense perspectives in a wide range of complex matters, including personal injury, maritime, oil and gas, commercial litigation, aviation, environmental, regulatory, and catastrophic casualty cases.\n\nMr. von Sternberg’s litigation background includes involvement in some of the most significant industrial, maritime, aviation, and energy-related matters in Texas and beyond. His experience includes investigations and litigation arising from refinery explosions, vessel casualties, air crashes, environmental incidents, oil and chemical spills, offshore platform matters, commercial disputes, and personal injury claims. He has worked with aviation, marine, energy, oilfield, maritime, and international insurance clients, including matters involving P&I Clubs and complex commercial dockets.\n\nOver the course of his career, Mr. von Sternberg has handled high-stakes investigations and litigation connected to major incidents such as the 1989 Phillips Petroleum plant explosion in Pasadena, Texas; the M/V MEGA BORG explosion off the coast of Galveston; the Tan-Sahsa 727 crash in Tegucigalpa, Honduras; and the M/T OMI CHARGER explosion at the Galveston Anchorage. He also served as part of the legal team representing Halliburton Energy Services, Inc. in the Multi-District Litigation arising from the BP/MODU DEEPWATER HORIZON disaster, where he was involved in discovery, witness and expert preparation, forensic investigation issues, trial strategy, and settlement documentation.\n\nMr. von Sternberg’s work has taken him across the United States and internationally in connection with serious casualty investigations, evidence preservation, witness interviews, and complex litigation support. His experience includes investigations in Chile, the Philippines, Bosnia, Croatia, India, and Colombia, reflecting the depth and scope of his litigation practice.\n\nIn addition to his trial and litigation experience, Mr. von Sternberg has briefed and argued appeals before the United States Court of Appeals for the Fifth Circuit and has prepared writs of certiorari to the United States Supreme Court. He has also been recognized by his peers, including being named a Texas Super Lawyer on multiple occasions, listed among the Houston Top 50 and Texas Top 100 by H Texas magazine, and receiving an AV Preeminent rating from Martindale-Hubbell, its highest rating for legal ability and ethical standards.",
    category: "associates",
  },
  {
    id: "zirwa-sheikh",
    name: "Zirwa Basser Sheikh",
    position: "Associate",
    image: "/images/headshots/Zirwa photoshoot.png",
    bio: "Zirwa Baseer Sheikh is a Texas trial attorney focused on personal injury litigation. She brings a valuable and strategic perspective to Aqrawi & Associates, having worked on both sides of injury claims, first in insurance defense and now as an advocate for injured individuals on the plaintiff side.Zirwa’s background in insurance defense gives her a strong understanding of how insurance companies evaluate claims, prepare defenses, and attempt to minimize payouts. Today, she uses that experience to better anticipate defense strategies, strengthen her clients’ cases, and pursue the compensation they deserve. Her transition to plaintiff-side litigation reflects her commitment to helping individuals and families who have been injured due to the negligence of others.Born in Pakistan and raised in Irving, Texas, Zirwa understands the importance of perseverance, advocacy, and service. She earned her Bachelor of Arts in Psychology from Texas A&M University, graduating with honors in just three years, and later earned her Juris Doctor from Texas Tech University School of Law. Her educational background in psychology gives her a deeper understanding of people, communication, and the human impact of injury cases.Throughout her legal career, Zirwa has handled a wide range of civil litigation and personal injury matters, including motor vehicle accidents, trucking accidents, premises liability claims, insurance disputes, and complex injury cases. She is known for her preparation, attention to detail, and ability to guide clients through the litigation process with clarity and confidence.Zirwa understands that injured clients are often facing physical pain, emotional stress, and uncertainty about the future. Her goal is to make the legal process more understandable and less overwhelming while providing strong, strategic representation. She is committed to protecting her clients’ rights, holding responsible parties accountable, and helping each client move toward the best possible outcome.",
    category: "associates",
  },
  {
    id: "milton-hammond",
    name: "Milton Hammond",
    position: "Attorney at Law",
    image: "",
    bio: "Milton Hammond serves as an Associate Attorney in the firm’s litigation department, bringing decades of legal experience and nearly 30 years of litigation experience to his role. Since joining the firm in January 2025, Milton has handled a wide range of litigation responsibilities, including trials, mediations, depositions, written discovery, case evaluation, and client communication.\n\nMilton’s practice focuses on plaintiff’s personal injury litigation, including car accidents, medical malpractice, premises liability, and other injury-related matters. He has also handled commercial litigation and insurance defense matters, giving him a broad understanding of litigation strategy from multiple perspectives. Milton is admitted to practice in Texas state and federal courts and before the United States Supreme Court.\n\nKnown for being proactive, driven, compassionate, and client-focused, Milton values direct personal communication with clients and co-workers. He believes that strong communication is essential to helping clients feel informed and supported throughout the litigation process. When working with clients who are stressed, injured, or uncertain, Milton takes time to listen carefully, ask thoughtful questions, and offer practical guidance.\n\nMilton is motivated by the opportunity to make a positive difference in clients’ lives. He enjoys trying cases, resolving cases, and helping clients move forward. Among his professional accomplishments, Milton has helped secure significant trial results, including serving as co-counsel in a medical malpractice case that resulted in a $4 million verdict. He also successfully tried a commercial real estate commission case, obtained a verdict, and later retried and won the case again after appeal.\n\nBorn and raised in Texas, Milton grew up in Dallas and moved to Houston in 2020. Outside of work, he enjoys music, rock climbing, and camping. A unique fact about Milton is that he got married in Hawaii and previously worked in the Los Angeles office of a Dallas-based law firm.",
    category: "associates",
  },

  // STAFF
  {
    id: "agha-sikander",
    name: "Agha Mahnoor Sikander",
    position: "Litigation Paralegal",
    image: "",
    bio: "Agha Mahnoor is a Senior Paralegal at Aqrawi & Associates, where she provides litigation and case management support in personal injury and immigration matters. With nearly 8 years of legal experience, she has developed a strong background in litigation support, case strategy implementation, client relations, trial preparation, and complex case management.\n\nPrior to joining Aqrawi & Associates in 2023, Agha served as both a Litigation Paralegal and an Immigration Paralegal, gaining extensive experience in personal injury litigation, discovery, legal research, court filings, case analysis, and immigration case processing. Throughout her career, she has assisted attorneys through all stages of litigation, including case development, discovery coordination, deposition preparation, medical records review, and trial preparation.\n\nKnown for her attention to detail, organizational skills, and commitment to client service, Agha works closely with attorneys, clients, experts, and opposing counsel to help ensure cases progress efficiently and effectively. She is dedicated to providing clients with clear communication, responsive support, and guidance throughout the legal process.\n\nAgha is currently pursuing a Bachelor of Science in Criminal Justice with a concentration in Corrections and a minor in Psychology at the University of Houston–Downtown. She is expected to graduate in December 2026 and plans to attend law school in Fall 2027 as she continues pursuing her goal of becoming an attorney. Agha is a member of the National Society of Collegiate Scholars and has consistently earned Dean’s List recognition throughout her academic career.\n\nFluent in Urdu, Agha is able to communicate effectively with clients from diverse backgrounds and assist them in navigating complex legal matters. Outside of her professional responsibilities, Agha enjoys reading, fitness and wellness, community involvement, and continuing her legal education.",
    category: "staff",
  },
  {
    id: "iwan-calderon",
    name: "Iwan Alberto Mendoza Calderon",
    position: "Senior Litigation Paralegal",
    image: "",
    bio: "Iwan Alberto Mendoza Calderon serves as a Senior Litigation Paralegal in the firm’s personal injury litigation department, bringing more than 15 years of legal experience to his role. Since joining the firm in December 2023, Iwan has assisted attorneys throughout all phases of litigation, including drafting legal documents, preparing discovery responses, reviewing and organizing medical records, coordinating depositions and mediations, maintaining litigation calendars, conducting legal research, and managing high-volume case dockets.\n\nIwan primarily supports personal injury matters, including motor vehicle accidents, trucking accidents, premises liability claims, insurance disputes, discovery management, medical record review, and trial preparation. Known for being organized, dependable, detail-oriented, responsive, proactive, and solution-oriented, he is committed to helping clients feel informed, respected, and supported throughout the litigation process.\n\nIwan brings a unique international legal background to the firm. He earned a law degree from Universidad La Salle in Mexico City, where he graduated with Honorable Mention, and later earned his Juris Doctor from the Inter American University of Puerto Rico School of Law. His legal career includes experience as a litigation paralegal, case manager, law clerk, appellate court legal officer in Mexico, teaching assistant, university law professor, and published legal scholar. His article, “Principios Generales de la Cadena de Custodia – Cadena de Evidencia,” was published by Mexico’s Federal Institute of Public Defense.\n\nFluent in both English and Spanish, including legal terminology, Iwan helps bridge communication gaps for Spanish-speaking clients by ensuring they understand the legal process, case developments, and important documents in their preferred language. Iwan is also a Texas Notary Public and has completed international legal studies through the China Law Summer Program at the University of Communications in Beijing.\n\nOutside of work, he enjoys reading, legal research, studying history, traveling, playing video games, collecting action figures, and spending quality time with family and friends.",
    category: "staff",
  },
  {
    id: "susan-von-sternberg",
    name: "Susan von Sternberg",
    position: "Senior Litigation Paralegal",
    image: "/images/headshots/susan photo .png",
    bio: "Susan von Sternberg is a Certified Paralegal with more than 16 years of experience in the legal field. She has a diverse background in civil commercial litigation, personal injury, wills and probate, mergers and acquisitions, and patent and trademark matters. Her broad legal experience allows her to support complex cases with strong organization, attention to detail, and a practical understanding of litigation and case management.\n\nSusan earned her Bachelor of Business Administration in Computer Information Systems from the University of Houston-Downtown. Her background in technology, business, marketing, and entrepreneurship gives her a unique perspective in the legal field, especially when managing projects, implementing systems, coordinating deadlines, and supporting attorneys and clients through matters of varying complexity.\n\nKnown for being goal-oriented, organized, and client-focused, Susan brings strong communication skills and a commitment to building lasting professional relationships. She is experienced in managing deadlines, handling detailed tasks, and helping ensure that cases and projects move forward efficiently.\n\nIn addition to her legal career, Susan continues to embrace innovation, including the use of AI technology and modern business tools to improve efficiency and productivity. Together with her husband, Jerry C. von Sternberg, Susan brings valuable experience and dedication to Aqrawi & Associates as part of a strong litigation support team.",
    category: "staff",
  },
  {
    id: "rekhan-ismail",
    name: "Rekhan Ismail",
    position: "Legal Assistant",
    image: "/images/headshots/Rekhan headshot.png",
    bio: "Rekhan Ismail is a detail-oriented and dependable Legal Assistant with experience in legal support, administrative operations, and client service. In his role, he assists with personal injury matters by supporting case management, preparing and organizing legal documents, reviewing medical records, analyzing police reports for liability, and helping prepare comprehensive demand packages for insurance companies.\n\nRekhan supports attorneys and case managers through document preparation, client communication, and careful organization of case files. He understands the importance of maintaining confidentiality, accuracy, and professionalism in every matter he handles. His ability to coordinate with clients, medical providers, and insurance representatives helps ensure that cases continue moving forward efficiently and that important details are properly managed.\n\nIn addition to his legal experience, Rekhan has provided administrative support in an academic setting at the University of Houston–Downtown, where he assisted with data management, scheduling, and office operations. This background strengthened his ability to manage sensitive information, multitask, and provide reliable support in fast-paced professional environments.\n\nRekhan holds a Bachelor of Arts in Political Science with a minor in Philosophy from the University of Houston–Downtown. Outside of his professional work, he is actively involved in community service, including humanitarian donation efforts, voting advocacy, and youth development.",
    category: "staff",
  },
  {
    id: "edwin-dominguez",
    name: "Edwin Dominguez",
    position: "Legal Assistant",
    image: "",
    bio: "Edwin Dominguez serves as a Legal Assistant in the firm’s pre-litigation department, where he assists case managers and attorneys with a variety of responsibilities, including answering incoming calls, responding to emails, preparing legal documents, and helping keep case materials organized. He supports both pre-litigation and litigation matters, with experience assisting on personal injury cases.\n\nKnown for being dependable, patient, and responsive, Edwin takes pride in helping clients feel comfortable and supported throughout the legal process. He understands that many clients come to the firm during stressful and uncertain times, and he approaches each interaction with empathy, patience, and a commitment to finding answers. His background in retail sales helped him develop strong communication skills, which he now uses to build trust with clients and work effectively with his team.\n\nEdwin is fluent in English and Spanish. Born and raised in Houston, Texas, he enjoys playing soccer, jogging, working out, and walking his dog outside of work.",
    category: "staff",
  },
  {
    id: "eunge-yi",
    name: "Eunge Yi",
    position: "Senior Case Manager",
    image: "",
    bio: "Eunge Yi serves as a Senior Case Manager in the firm’s pre-litigation department, bringing 30 years of legal field experience and 5 years of dedicated service with the firm. Eunge focuses on managing complex personal injury cases, including matters involving car accidents, trucking accidents, premises liability, medical treatment coordination, insurance claims, and litigation support.\n\nKnown for being organized, communicative, compassionate, detail-oriented, responsive, dependable, patient, efficient, and client-focused, Eunge takes pride in guiding clients through the personal injury process with clarity and care. Eunge understands that clients are often facing pain, uncertainty, and stress, and works to make the process easier by maintaining regular communication, providing case status updates, and patiently explaining each step along the way.\n\nEunge is motivated by achieving shared goals with clients and helping them pursue the compensation they deserve for their pain and suffering. Over the years, Eunge has helped support cases that resulted in multiple six-figure settlements and has received positive feedback from clients for professionalism, communication, and dedication.\n\nEunge speaks Korean and brings a strong multicultural perspective, having been born in Korea, immigrated to the United States at age 4, and raised in California. Outside of work, Eunge enjoys cooking, watching movies, and reading. Eunge is also known for impeccable penmanship and hopes to one day visit Bora Bora.",
    category: "staff",
  },
  {
    id: "glenda-castillo",
    name: "Glenda Castillo",
    position: "Case Manager",
    image: "",
    bio: "Glenda Castillo serves as a Case Manager with 10 years of experience in the legal field. In her role, Glenda acts as a primary point of contact for clients and helps manage personal injury cases from start to finish, with a focus on clients who have been injured in car accidents.\n\nKnown for being organized, compassionate, detail-oriented, responsive, dependable, patient, efficient, and client-focused, Glenda is committed to helping clients feel supported throughout the legal process. She understands that clients may be dealing with pain, stress, and uncertainty after an accident, and she takes pride in being someone they can count on for timely communication and genuine care.\n\nGlenda has experience in personal injury matters, including car accidents, trucking accidents, premises liability, medical treatment coordination, insurance claims, and litigation support. Her background in office management and case management has helped her develop strong organizational skills, patience, and the ability to manage cases efficiently while keeping clients informed.\n\nFluent in Spanish, Glenda is able to assist Spanish-speaking clients with clear communication and support. She also holds a degree in Child Development, which reflects her patience, understanding, and ability to work with people with care and attention.\n\nGlenda was raised in Houston, Texas, in the East End area. Outside of work, she enjoys going to the beach and watching the sunset. A fun fact about Glenda is that she never learned how to write in cursive, which often surprises people when she tells them.",
    category: "staff",
  },
  {
    id: "nathaly-portillo",
    name: "Nathaly Portillo",
    position: "Case Manager",
    image: "",
    bio: "Nathaly Portillo serves as a Personal Injury Case Manager at the firm, bringing 2 years of experience in the personal injury field and 2 years of dedicated service with the firm. Originally from El Salvador, Nathaly has grown within the firm through several roles, including Receptionist, Legal Assistant, and now Personal Injury Case Manager. These experiences have given her a strong understanding of client relations, case management, legal support, and the day-to-day operations of a personal injury law firm.\n\nIn her role, Nathaly serves as a primary point of contact for clients throughout their case. She assists with client communication, case management, file organization, medical records, treatment coordination, insurance claims, documentation, and attorney support. Nathaly is committed to making sure every client feels informed, supported, and confident throughout the legal process.\n\nKnown for being compassionate, detail-oriented, dependable, patient, honest, efficient, responsive, and client-focused, Nathaly takes pride in building strong relationships with clients during what is often a difficult time in their lives. She understands that personal injury clients may be facing physical, emotional, and financial challenges, and she works to reduce their stress by providing clear communication, consistent updates, and careful case management.\n\nThe most rewarding part of Nathaly’s work is helping clients achieve successful outcomes and seeing cases resolve for the maximum available policy limits. She is motivated by the opportunity to make a positive difference in people’s lives, help clients feel supported, and contribute to meaningful results.\n\nNathaly is fluent in English and Spanish. Outside of work, she enjoys planning weddings and quinceañeras, which allows her to express her creativity while strengthening her organizational and coordination skills. Her faith and family are important parts of her life and continue to inspire her values of service, compassion, integrity, and personal growth.",
    category: "staff",
  },
  {
    id: "valerie-v",
    name: "Valerie V.",
    position: "Case Manager",
    image: "",
    bio: "Valerie V. serves as a Pre-Litigation Case Manager at the firm, bringing 6 years of experience in the legal field and more than 2 years of dedicated service with the firm. In her role, Valerie manages client cases and assists with personal injury matters, including regular cases and higher policy cases.\n\nValerie is known for being responsive, dependable, patient, and a strong problem-solver. She is committed to helping clients get the care they need and guiding them through the pre-litigation process with professionalism and support. Her prior experience in intake, closings, and reductions has helped her understand multiple stages of the personal injury process and better assist clients as their cases move forward.\n\nFluent in Spanish, Valerie is able to communicate with and support Spanish-speaking clients throughout their case. She takes pride in helping clients reach favorable outcomes, especially when the firm is able to obtain policy limits on behalf of clients.",
    category: "staff",
  },
  {
    id: "raven-n",
    name: "Raven N.",
    position: "Case Manager",
    image: "",
    bio: "Raven N. serves as a Case Manager in the firm’s pre-litigation department, bringing 4 years of legal experience and 3 years of dedicated service with the firm. In her role, Raven assists personal injury clients throughout the pre-litigation process by managing cases, communicating with clients, and helping cases move efficiently toward resolution.\n\nKnown for being detail-oriented, dependable, compassionate, organized, and client-focused, Raven is committed to keeping clients informed and supported throughout their case. She understands that the legal process can feel overwhelming, especially for clients dealing with injuries or uncertainty, and she approaches each client interaction with patience, empathy, and clear communication.\n\nRaven holds a degree in Criminal Justice and brings a diverse background in sales, athletics, marketing, and fashion, all of which have helped strengthen her communication, discipline, and problem-solving skills. She is motivated by achieving results and helping clients move forward with confidence.\n\nOriginally from Michigan, Raven enjoys working out and staying active outside of work. She is also a proud cat enthusiast.",
    category: "staff",
  },
  {
    id: "maria-hernandez",
    name: "Maria Hernandez",
    position: "Case Manager",
    image: "",
    bio: "Maria Hernandez serves as a Case Manager at the firm, where she assists clients with personal injury and car accident cases. With 2 years of experience in the legal field and 2 years with the firm, Maria helps support clients throughout the case process, with a focus on Spanish-speaking clients and minimum policy cases.\n\nKnown for being dependable, organized, client-focused, and a problem-solver, Maria is committed to making clients feel supported and heard. She understands that clients may be dealing with stress, injuries, and uncertainty, and she approaches each situation with patience and care. Maria takes pride in listening calmly, answering questions, and helping clients feel more comfortable throughout their case.\n\nMaria’s background in customer service helped prepare her for her current role by strengthening her communication skills and ability to assist people with professionalism and compassion. She is fluent in Spanish and uses her bilingual skills to help Spanish-speaking clients better understand the legal process.\n\nOriginally from Argentina and raised in Houston, Texas, Maria is motivated by her family and takes pride in how much she has learned and accomplished in her role. Outside of work, she enjoys shopping and spending time with her family.",
    category: "staff",
  },
  {
    id: "sandra-rosas",
    name: "Sandra Rosas",
    position: "Case Manager",
    image: "",
    bio: "Sandra Rosas serves as a Case Manager in the firm’s personal injury department, where she assists clients throughout the pre-litigation process. With 2 years of experience in the legal field and 2 years with the firm, Sandra helps clients with personal injury matters by maintaining communication, coordinating treatment, and helping guide them through important steps in their case.\n\nSandra is known for being organized, compassionate, responsive, and patient. She understands that clients are often dealing with pain, stress, and uncertainty after an accident, and she works to make the process easier by listening to their concerns, explaining the treatment process, and helping them feel supported along the way. Her background in customer service helped strengthen her patience, communication skills, and ability to assist clients with care and professionalism.\n\nSandra is fluent in Spanish and is committed to helping clients feel comfortable and understood. She is motivated by her children and by the opportunity to help clients during difficult times. Sandra takes pride in everything she has learned in the personal injury field and continues to grow in her role as she supports clients and the firm’s case management team.\n\nOutside of work, Sandra enjoys spending time with her children and family.",
    category: "staff",
  },
  {
    id: "patricia-sierra",
    name: "Patricia Sierra",
    position: "Personal Injury Claims Professional",
    image: "",
    bio: "Patricia Sierra has been with Aqrawi Law Firm for the past 3 years and brings more than 30 years of experience handling personal injury claims. With decades of knowledge in the claims process, Patricia understands the importance of guiding clients with care, professionalism, and clear communication during a difficult time.\n\nPatricia is dedicated to helping clients navigate their personal injury cases and supporting them throughout each stage of the process. Her experience, attention to detail, and commitment to client service allow her to assist clients as they work toward the best possible outcome.",
    category: "staff",
  },
  {
    id: "liz-reyes",
    name: "Liz Reyes",
    position: "Intake Specialist",
    image: "",
    bio: "Liz Reyes serves as an Intake Specialist at the firm, where she helps new clients begin the legal process with clarity and support. With 5 years of experience in the legal field and 2 years with the firm, Liz assists clients during the intake stage by helping them get signed up, starting their file, and guiding them through the first important steps after an accident.\n\nLiz has experience with personal injury and insurance claims, and she is committed to helping clients understand their rights after an auto accident. Known for her structured and hardworking approach, Liz takes pride in making clients feel comfortable, supported, and reassured that the firm is on their side.\n\nFluent in Spanish, Liz is able to assist Spanish-speaking clients and explain the process in a way that is clear and easy to understand. She is motivated by knowing that clients are getting the help they deserve and takes pride in helping them begin their case.\n\nOriginally from Mexico and raised in Houston, Texas, Liz enjoys spending time with two children and going on trail walks outside of work. A fun fact about Liz is that she does not know how to ride a bike.",
    category: "staff",
  },
  {
    id: "klarissa-avila",
    name: "Klarissa Avila",
    position: "Intake Assistant",
    image: "",
    bio: "Klarissa Avila serves as an Intake Assistant at the firm, where she helps clients begin the claims process as smoothly and efficiently as possible. With 9 months of experience in the legal field and 9 months with the firm, Klarissa assists with important intake responsibilities, including filing claims promptly and sending Letters of Representation in a timely manner.\n\nKnown for being organized, efficient, detail-oriented, caring, empathetic, and solution-focused, Klarissa is committed to going above and beyond for clients from the very beginning of their case. Her background in customer service helped prepare her for this role by strengthening her patience, understanding, and ability to assist clients with professionalism and care.\n\nKlarissa is fluent in Spanish and takes pride in helping clients feel heard, supported, and taken care of. She is motivated by her daughter, as well as her desire to continue growing personally and professionally while building a better future.\n\nBorn and raised in Houston, Texas, Klarissa enjoys spending time outdoors and exploring parks with her daughter outside of work.",
    category: "staff",
  },
  {
    id: "dahlia-gamez",
    name: "Dahlia Gamez",
    position: "Receptionist / Legal Assistant",
    image: "/images/headshots/dahlia .png",
    bio: "Dahlia Gamez serves as a Receptionist and Legal Assistant at the firm, where she is often the first point of contact for clients. In her role, Dahlia greets clients, manages incoming calls, schedules appointments, organizes case files, and supports attorneys with administrative and legal tasks that help keep cases moving efficiently.\n\nDahlia assists with communication between clients, medical providers, insurance adjusters, and the legal team. She understands that many clients contact the firm during stressful and uncertain times, and she takes pride in offering reassurance, clarity, and support from the very beginning. Known for being detail-oriented, organized, dependable, compassionate, and caring, Dahlia is committed to making every client feel heard and supported.\n\nHer previous experience in a doctor’s office helped her develop strong communication skills, multitasking abilities, and a calm, professional approach in fast-paced environments. Fluent in Spanish, Dahlia is able to assist Spanish-speaking clients and help them feel more comfortable throughout the process.\n\nBorn and raised in Houston, Texas, Dahlia comes from a family with roots in Mexico. Outside of work, she enjoys spending time with her daughter, staying active outdoors and at the gym, reading, learning new things, cooking, baking, and Pilates.",
    category: "staff",
  },
  {
    id: "kathy-giron",
    name: "Kathy Giron",
    position: "Intern – Legal Assistant",
    image: "/images/headshots/kathy .png",
    bio: "Kathy Giron serves as an Intern Legal Assistant with the firm. After excelling in her studies, Kathy was awarded the opportunity to intern as a Legal Assistant, allowing her to gain hands-on experience and continue learning about the legal industry.\n\nIn her role, Kathy assists with client communication, case organization, document preparation, and administrative support. She is dependable, detail-oriented, and eager to learn, while also showing strong ability in the work she performs. Kathy takes pride in supporting both clients and the legal team with professionalism, kindness, and care.\n\nOriginally from San Antonio, Texas, Kathy comes from a proud Salvadoran family. Outside of work, she enjoys playing soccer and writing.",
    category: "staff",
  },
  {
    id: "karla-rodriguez",
    name: "Karla Rodriguez",
    position: "Marketing Specialist",
    image: "",
    bio: "Karla Rodriguez serves as the firm’s Senior Marketing Specialist, bringing 20 years of experience in the legal field and 2 years of dedicated service with the firm. In her role, Karla focuses on public relations, community outreach, marketing, advertising, and client relations, helping strengthen the firm’s connection with the community and the clients it serves.\n\nKnown as a problem-solver and “the fixer,” Karla is committed to helping her team, supporting clients, and finding solutions when challenges arise. Her background in advertising sales and corporate event planning has helped her develop strong communication, organization, negotiation, and relationship-building skills. She also has experience in personal injury, defense, marketing, social media, event planning, and litigation support.\n\nKarla believes in being honest, sincere, and accessible with clients. She understands that clients may feel stressed, injured, or uncertain about the legal process, and she works to make them feel heard, protected, and supported. She takes the time to listen, explain the pre-litigation process, and provide reassurance so clients feel more comfortable moving forward.\n\nFluent in Spanish, Karla is able to connect with and assist Spanish-speaking clients with care and clarity. She is also certified to teach harassment prevention classes in English and Spanish in California. Karla is motivated by her team, whom she considers her second family, and she takes pride in being part of the firm’s continued growth.\n\nOriginally from Matamoros, Tamaulipas, and raised in Houston, Texas, Karla enjoys yoga, trying new cuisine, attending local concerts, and traveling for music festivals. She also enjoys heavy metal and classical music, is a skilled dancer, and competed as a fitness figure competitor for 7 years.",
    category: "staff",
  },
  {
    id: "mayela-figueroa",
    name: "Mayela Figueroa",
    position: "Bills and Records Clerk",
    image: "/images/headshots/meyla headshot 2.png",
    bio: "Mayela Figueroa serves as the Bills and Records Manager at Aqrawi & Associates Law Firm, where she plays an important role in supporting both the personal injury and immigration departments. With more than 4 years of experience in immigration-related matters and 2 years of experience handling accident and personal injury claims, Mayela brings strong organization, knowledge, and dedication to every case she supports.\n\nIn her role, Mayela manages medical and billing records, coordinates documentation, communicates with providers and insurance companies, and helps maintain accurate case files. Her work helps ensure that important records are properly organized and available to support the progress and resolution of each case.\n\nFluent in English and Spanish, Mayela assists clients from diverse backgrounds and helps promote clear communication throughout the legal process. She is known for her attention to detail, dependability, compassion, and client-focused approach. Mayela understands that many clients come to the firm during difficult times, and she works to make the process as smooth and stress-free as possible by providing timely support and careful attention to each matter.\n\nIn addition to her legal experience, Mayela is a Certified Occupational Therapy Assistant and has a strong background in healthcare and client advocacy. Her healthcare experience enhances her ability to work with medical records, understand treatment documentation, and support clients with professionalism and empathy.\n\nOutside of work, Mayela enjoys spending time with her family, staying active, and continuing her education and professional development. She is passionate about helping others and takes pride in being part of a team that makes a positive difference in clients’ lives.",
    category: "staff",
  },
];
