export interface TeamMember {
  id: string;
  name: string;
  position: string;
  image: string;
  bio: string;
  category: "staff" | "management" | "associates" | "partners";
}

export const TEAM_MEMBERS: TeamMember[] = [
  // PARTNERS
  {
    id: "walat-aqrawi",
    name: "Walat Aqrawi",
    position: "Founding Partner",
    image: "/images/headshots/Walat Aqrawi.webp",
    bio: "Walat Aqrawi is the Founding Partner of Aqrawi Law Firm. With decades of litigation experience, he has represented clients in high-stakes personal injury, commercial disputes, and complex litigation. He is dedicated to aggressive advocacy, unwavering integrity, and securing maximum recoveries for injury victims and their families.",
    category: "partners",
  },
  {
    id: "aaron-aiken",
    name: "Aaron Aiken",
    position: "Partner",
    image: "/images/headshots/Aaron Aiken.webp",
    bio: "Aaron Aiken is a Partner specializing in litigation, corporate representation, and personal injury law. He has a track record of securing positive resolutions and advocating fiercely on behalf of our clients.",
    category: "partners",
  },

  // MANAGEMENT
  {
    id: "mohammed-khallaf",
    name: "Mohammed Khallaf",
    position: "General Manager",
    image: "/images/headshots/headshot mohammed.png",
    bio: "Mohammed Khallaf serves as General Manager at Aqrawi & Associates, bringing over 15 years of corporate leadership and operational management. He oversees the firm's strategic growth, international partnerships, and daily operations, ensuring that the firm's legal team has the resources needed to deliver outstanding client representation.",
    category: "management",
  },
  {
    id: "monica-toscano",
    name: "Monica Toscano",
    position: "Assistant Manager",
    image: "/images/headshots/monica headshot.png",
    bio: "Monica Toscano serves as Assistant Manager at Aqrawi & Associates, where she brings more than 15 years of experience in administration, client service, records management, and operational support. As a bilingual professional fluent in English and Spanish, Monica is dedicated to helping clients feel informed, supported, and confident throughout every stage of their legal matter.\n\nBorn in McAllen, Texas, and raised in Houston, Monica comes from a humble background that taught her the value of hard work, perseverance, and integrity. Before entering the legal field, she held leadership and administrative roles in public health, healthcare administration, banking, and insurance, gaining valuable experience in client relations, compliance, operations management, and problem-solving.",
    category: "management",
  },
  {
    id: "mahmood-noaman",
    name: "Mahmood Noaman",
    position: "Iraq Branch Manager / Marketing",
    image: "/images/headshots/Photo headshot 1.png",
    bio: "Mahmood Noaman serves as the Iraq Branch Manager / Marketing at Aqrawi & Associates, overseeing our operations and marketing directions in the region. He leads regional client communication and coordinates international business development.",
    category: "management",
  },

  // ASSOCIATES
  {
    id: "jerry-von-sternberg",
    name: "Jerry C. von Sternberg",
    position: "Associate",
    image: "/images/headshots/jerry headshot.png",
    bio: "Jerry C. von Sternberg is an Associate Attorney at Aqrawi & Associates. He focuses on case analysis, drafting motions, and advising clients on litigation strategies to achieve the best outcomes.",
    category: "associates",
  },
  {
    id: "zirwa-sheikh",
    name: "Zirwa Basser Sheikh",
    position: "Associate",
    image: "/images/headshots/Zirwa photoshoot.png",
    bio: "Zirwa Basser Sheikh is an Associate at the firm, bringing strong legal research skills and a dedication to advocating for personal injury victims.",
    category: "associates",
  },
  {
    id: "milton-hammond",
    name: "Milton Hammond",
    position: "Associate",
    image: "",
    bio: "Milton Hammond serves as an Associate Attorney, specializing in litigation prep and client advocacy.",
    category: "associates",
  },

  // STAFF
  {
    id: "agha-sikander",
    name: "Agha Mahnoor Sikander",
    position: "Staff Member",
    image: "",
    bio: "Agha Mahnoor Sikander provides essential administrative and case support services to the legal team.",
    category: "staff",
  },
  {
    id: "iwan-calderon",
    name: "Iwan Alberto Mendoza Calderon",
    position: "Staff Member",
    image: "",
    bio: "Iwan Alberto Mendoza Calderon assists with legal translations, case documentation, and client coordination.",
    category: "staff",
  },
  {
    id: "susan-von-sternberg",
    name: "Susan von Sternberg",
    position: "Staff Member",
    image: "/images/headshots/susan photo .png",
    bio: "Susan von Sternberg provides administrative support, schedules consultations, and manages firm documents.",
    category: "staff",
  },
  {
    id: "rekhan-ismail",
    name: "Rekhan Ismail",
    position: "Staff Member",
    image: "/images/headshots/Rekhan headshot.png",
    bio: "Rekhan Ismail assists our case managers with client communication and court filing preparations.",
    category: "staff",
  },
  {
    id: "edwin-dominguez",
    name: "Edwin Dominguez",
    position: "Staff Member",
    image: "",
    bio: "Edwin Dominguez manages document compilation and handles paralegal operations support.",
    category: "staff",
  },
  {
    id: "eunge-yi",
    name: "Eunge Yi",
    position: "Staff Member",
    image: "",
    bio: "Eunge Yi supports the management with financial administration and case organization.",
    category: "staff",
  },
  {
    id: "glenda-castillo",
    name: "Glenda Castillo",
    position: "Staff Member",
    image: "",
    bio: "Glenda Castillo supports our attorneys in daily tasks and manages client file lifecycles.",
    category: "staff",
  },
  {
    id: "nathaly-portillo",
    name: "Nathaly Portillo",
    position: "Staff Member",
    image: "",
    bio: "Nathaly Portillo assists with scheduling, document filing, and administrative support.",
    category: "staff",
  },
  {
    id: "valerie-v",
    name: "Valerie V.",
    position: "Staff Member",
    image: "",
    bio: "Valerie V. provides front-desk support and coordinate scheduling of free legal evaluations.",
    category: "staff",
  },
  {
    id: "raven-n",
    name: "Raven N.",
    position: "Staff Member",
    image: "",
    bio: "Raven N. manages incoming client communications and database updates.",
    category: "staff",
  },
  {
    id: "maria-hernandez",
    name: "Maria Hernandez",
    position: "Staff Member",
    image: "",
    bio: "Maria Hernandez manages document filing, legal records, and scheduling tasks.",
    category: "staff",
  },
  {
    id: "sandra-rosas",
    name: "Sandra Rosas",
    position: "Staff Member",
    image: "",
    bio: "Sandra Rosas coordinates files, case updates, and provides paralegal support.",
    category: "staff",
  },
  {
    id: "patricia-sierra",
    name: "Patricia Sierra",
    position: "Staff Member",
    image: "",
    bio: "Patricia Sierra assists in legal administration and client intake operations.",
    category: "staff",
  },
  {
    id: "liz-reyes",
    name: "Liz Reyes",
    position: "Staff Member",
    image: "",
    bio: "Liz Reyes supports attorney scheduling, correspondence, and record management.",
    category: "staff",
  },
  {
    id: "klarissa-avila",
    name: "Klarissa Avila",
    position: "Staff Member",
    image: "",
    bio: "Klarissa Avila assists in client case development and filing preparations.",
    category: "staff",
  },
  {
    id: "dahlia-gamez",
    name: "Dahlia Gamez",
    position: "Staff Member",
    image: "/images/headshots/dahlia .png",
    bio: "Dahlia Gamez supports litigation preparation and client file management.",
    category: "staff",
  },
  {
    id: "kathy-giron",
    name: "Kathy Giron",
    position: "Staff Member",
    image: "/images/headshots/kathy .png",
    bio: "Kathy Giron assists with client relations and daily office administration.",
    category: "staff",
  },
  {
    id: "karla-rodriguez",
    name: "Karla Rodriguez",
    position: "Staff Member",
    image: "",
    bio: "Karla Rodriguez supports litigation attorneys with case organization and research.",
    category: "staff",
  },
  {
    id: "mayela-figueroa",
    name: "Mayela Figueroa",
    position: "Staff Member",
    image: "/images/headshots/meyla headshot 2.png",
    bio: "Mayela Figueroa coordinates marketing plans and firm administrative tasks.",
    category: "staff",
  },
];
