export interface TeamMember {
  id: string;
  name: string;
  position: string;
  image: string;
  bio: string;
  category: "partners" | "management" | "associates" | "staff";
}

export const TEAM_MEMBERS: TeamMember[] = [
  // PARTNERS
  {
    id: "walat-aqrawi",
    name: "Walat Aqrawi",
    position: "Founding & Managing Partner",
    image: "/images/headshots/headshotwalat.jpeg",
    bio: "Walat Aqrawi is the Founding & Managing Partner of Aqrawi & Associates and a highly respected personal injury attorney with a distinguished legal career in Texas and across the United States. Born in Kurdistan in 1973, he immigrated to the United States from Iraq, driven by a strong commitment to justice, opportunity, and the rule of law.\n\nMr. Aqrawi made history as the first Kurdish-American attorney licensed to practice law in the State of Texas and among the earliest Kurdish immigrants from Iraq to establish a successful legal career in the United States. His journey reflects resilience, leadership, and dedication to the legal profession.\n\nDuring the First Gulf War, he became the first attorney to successfully facilitate the legal immigration of an Iraqi national to the United States—achieving this during a time of extraordinary legal and political complexity. This milestone demonstrated exceptional legal skill and humanitarian commitment.\n\nIn addition to private practice, Mr. Aqrawi has served as legal counsel for multiple foreign consulates in the United States, including the Consulate of the Kingdom of Saudi Arabia in Texas, advising on diplomatic, civil, and legal matters.\n\nRecognized as a top attorney in Texas, his practice focuses on personal injury law, including automobile accidents, catastrophic injuries, liability disputes, and complex insurance negotiations. As Founding & Managing Partner, he remains personally involved in cases to ensure clients receive dedicated, high-quality representation.\n\nMr. Aqrawi’s legal philosophy is rooted in justice, accountability, and compassion, with a continued commitment to protecting the rights of injury victims and their families.",
    category: "partners",
  },
  {
    id: "aaron-aiken",
    name: "Aaron Aiken",
    position: "Partner",
    image: "/images/headshots/Aaron Aiken.webp",
    bio: "Aaron Aiken is a Partner at Aqrawi & Associates and a driving force behind the firm’s continued success. Known for his dedication, experience, and tireless work ethic, Mr. Aiken plays a leading role across a wide range of cases, delivering strategic insight and consistent results.\n\nSince the early days of the firm, Mr. Aiken has been instrumental in its growth and evolution, helping shape the high standard of excellence that defines Aqrawi & Associates today. His leadership, reliability, and sharp legal judgment have made him a trusted advocate for clients and a cornerstone of the firm.\n\nOriginally from Indiana, Mr. Aiken earned his undergraduate degree from Indiana University and his Juris Doctor from Thurgood Marshall School of Law. From the outset of his legal career, he has remained committed to representing clients with integrity and professionalism.\n\nRespected for his hands-on approach and attention to detail, Mr. Aiken is deeply involved in every case he handles.",
    category: "partners",
  },

  // MANAGEMENT
  {
    id: "mohammed-khallaf",
    name: "Mohammed Khallaf",
    position: "General Manager",
    image: "/images/headshots/headshot mohammed.png",
    bio: "Mohammed Khallaf serves as the General Manager of Aqrawi & Associates Law Firm, PLLC, where he has been a valued member of the team since June 2017. Since joining the firm, Mohammed has grown alongside the organization, beginning in legal support and advancing into a leadership role overseeing operations across the firm’s Houston, Laredo, San Antonio, and international offices.\n\nOriginally from Jeddah, Saudi Arabia, Mohammed moved to the United States in 2013 and built his education and professional career in Texas. He earned his Bachelor of Arts from the University of Houston in Political Science and Public Relations and later earned his Juris Doctor from Texas Southern University’s Thurgood Marshall School of Law. He also holds a Mediation Certification, a Global Studies and Research certification from the University of Houston Honors College, and completed coursework and received a certificate from the Institut Catholique de Paris, also known as the Catholic University of Paris, in Paris, France.\n\nMohammed’s experience shaped by his background in government, diplomacy, international affairs, consular matters, civic participation, political campaigns, and community leadership has strengthened his ability to communicate effectively, understand people from different backgrounds, and approach legal matters with strategy and professionalism. This experience benefits clients by helping him navigate sensitive issues, support strong communication, and assist in resolving matters efficiently.\n\nAs General Manager, Mohammed oversees the firm’s day-to-day operations, staff development, training, client relations, and case support systems. His work includes assisting with case management, negotiations, legal research, investigation, document coordination, medical records coordination, and pre-litigation and litigation support. He also helps support the firm’s work across personal injury, immigration, criminal, family, and international consular matters.\n\nMohammed understands that negotiation and conflict resolution are key factors in achieving successful case outcomes. He works to help move cases forward with clarity, organization, and practical problem-solving while ensuring that clients feel heard, informed, and supported throughout the process.\n\nFluent in English and Arabic, Mohammed is able to connect with clients from diverse backgrounds and communities. Outside of work, he enjoys music and DJing, soccer, horseback riding, fitness, martial arts, and boxing. He also maintains a strong interest in diplomacy, international law, human rights, business, politics, and global affairs.",
    category: "management",
  },
  {
    id: "monica-toscano",
    name: "Monica Toscano",
    position: "Assistant Manager",
    image: "/images/headshots/monica headshot.png",
    bio: "Monica Toscano serves as Assistant Manager at Aqrawi & Associates, where she brings more than 15 years of experience in administration, client service, records management, and operational support. As a bilingual professional fluent in English and Spanish, Monica is dedicated to helping clients feel informed, supported, and confident throughout every stage of their legal matter.\n\nBorn in McAllen, Texas, and raised in Houston, Monica comes from a humble background that taught her the value of hard work, perseverance, and integrity. Before entering the legal field, she held leadership and administrative roles in public health, healthcare administration, banking, and insurance, gaining valuable experience in client relations, compliance, operations management, and problem-solving.",
    category: "management",
  },
  {
    id: "mahmood-noaman",
    name: "Mahmood Noaman",
    position:
      "Iraq Branch Manager | Regional Public Relations & Marketing Manager",
    image: "/images/headshots/mahmoodJamal.jpeg",
    bio: "Mahmood Noaman serves as the Iraq Branch Manager and Regional Public Relations & Marketing Manager at Aqrawi & Associates PLLC, where he supports the firm’s operations, public relations, marketing efforts, and regional communication between Iraq and the United States. Since joining the firm, Mahmood has contributed to the organization’s growth through client relations, strategic communication, marketing coordination, and cross-cultural outreach.\n\nOriginally from Iraq and based between Baghdad, Iraq, and Houston, Texas, Mahmood has built a diverse academic and professional background across public relations, strategic communication, marketing, translation, client service, and international affairs. He earned his Bachelor of Arts in Public Relations and Strategic Communication Management from Texas Tech University, graduating Cum Laude with a 3.590 GPA. He also holds an Associate of Arts degree from Lone Star College and a Bachelor of Science degree in Biomedical Engineering from Al-Farahidi University in Iraq.\n\nMahmood’s experience has been shaped by his work in public relations, diplomatic communication, bilingual translation, marketing, media coordination, and client support. Before advancing into his current leadership role, he served as a Media and Public Relations Intern with the Embassy of the Republic of Iraq in Houston, where he managed Arabic-English communication, translated official documents and diplomatic correspondence, supported public relations, assisted with social media content, and helped coordinate diplomatic events and cultural initiatives. His background also includes several years of professional Arabic translation experience, where he assisted non-English speakers in legal and professional settings by providing accurate, confidential, and culturally appropriate communication support.\n\nAs Iraq Branch Manager and Regional Public Relations & Marketing Manager, Mahmood represents the firm’s Iraq office while coordinating directly with the U.S. team. His work includes supporting branch operations, client communication, public relations initiatives, marketing campaigns, media management, strategic messaging, document coordination, and regional outreach. He helps strengthen the connection between the firm’s U.S. and international operations while ensuring that clients and partners receive clear, professional, and responsive support.\n\nMahmood understands that effective communication, trust, and cultural awareness are essential to successful client relationships and organizational growth. His ability to work across different cultures, languages, and professional environments allows him to approach challenges with strategy, professionalism, and attention to detail. He is known for his organization, adaptability, problem-solving skills, and ability to perform effectively in diverse and fast-paced environments.\n\nIn addition to his academic and professional experience, Mahmood has earned certifications in Project Management Foundations, Customer Relationship Management, Human Resources, Digital Marketing and E-Commerce, Social Media Marketing, Media Relations, Canva, and Freelance Translation. He is also a commissioned Notary Public in the State of Texas and has been recognized by Texas Tech University through the President’s Honor List and Dean’s Honor List.\n\nFluent in Arabic and English, Mahmood is able to connect with clients, professionals, and communities from diverse backgrounds. His interests include public relations, digital marketing, international affairs, business development, client relations, communication strategy, and community engagement.",
    category: "management",
  },

  // ASSOCIATES
  {
    id: "jerry-von-sternberg",
    name: "Jerry C. von Sternberg",
    position: "Attorney at Law",
    image: "/images/headshots/jerry headshot.png",
    bio: "Jerry C. von Sternberg is an experienced litigation attorney and graduate of the University of Texas at Austin School of Law. Throughout his career, he has represented clients from both plaintiff and insurance defense perspectives in a wide range of complex matters, including personal injury, maritime, oil and gas, commercial litigation, aviation, environmental, regulatory, and catastrophic casualty cases.\n\nMr. von Sternberg’s litigation background includes involvement in some of the most significant industrial, maritime, aviation, and energy-related matters in Texas and beyond. His experience includes investigations and litigation arising from refinery explosions, vessel casualties, air crashes, environmental incidents, oil and chemical spills, offshore platform matters, commercial disputes, and personal injury claims. He has worked with aviation, marine, energy, oilfield, maritime, and international insurance clients, including matters involving P&I Clubs and complex commercial dockets.\n\nOver the course of his career, Mr. von Sternberg has handled high-stakes investigations and litigation connected to major incidents such as the 1989 Phillips Petroleum plant explosion in Pasadena, Texas; the M/V MEGA BORG explosion off the coast of Galveston; the Tan-Sahsa 727 crash in Tegucigalpa, Honduras; and the M/T OMI CHARGER explosion at the Galveston Anchorage. He also served as part of the legal team representing Halliburton Energy Services, Inc. in the Multi-District Litigation arising from the BP/MODU DEEPWATER HORIZON disaster, where he was involved in discovery, witness and expert preparation, forensic investigation issues, trial strategy, and settlement documentation.\n\nMr. von Sternberg’s work has taken him across the United States and internationally in connection with serious casualty investigations, evidence preservation, witness interviews, and complex litigation support. His experience includes investigations in Chile, the Philippines, Bosnia, Croatia, India, and Colombia, reflecting the depth and scope of his litigation practice.\n\nIn addition to his trial and litigation experience, Mr. von Sternberg has briefed and argued appeals before the United States Court of Appeals for the Fifth Circuit and has prepared writs of certiorari to the United States Supreme Court. He has also been recognized by his peers, including being named a Texas Super Lawyer on multiple occasions, listed among the Houston Top 50 and Texas Top 100 by H Texas magazine, and receiving an AV Preeminent rating from Martindale-Hubbell, its highest rating for legal ability and ethical standards.",
    category: "associates",
  },
  {
    id: "zirwa-sheikh",
    name: "Zirwa Basser Sheikh",
    position: "Associate",
    image: "/images/headshots/Zirwa photoshoot.png",
    bio: "Zirwa Baseer Sheikh is a Texas trial attorney focused on personal injury litigation. She brings a valuable and strategic perspective to Aqrawi & Associates, having worked on both sides of injury claims, first in insurance defense and now as an advocate for injured individuals on the plaintiff side.Zirwa’s background in insurance defense gives her a strong understanding of how insurance companies evaluate claims, prepare defenses, and attempt to minimize payouts. Today, she uses that experience to better anticipate defense strategies, strengthen her clients’ cases, and pursue the compensation they deserve. Her transition to plaintiff-side litigation reflects her commitment to helping individuals and families who have been injured due to the negligence of others.Born in Pakistan and raised in Irving, Texas, Zirwa understands the importance of perseverance, advocacy, and service. She earned her Bachelor of Arts in Psychology from Texas A&M University, graduating with honors in just three years, and later earned her Juris Doctor from Texas Tech University School of Law. Her educational background in psychology gives her a deeper understanding of people, communication, and the human impact of injury cases.Throughout her legal career, Zirwa has handled a wide range of civil litigation and personal injury matters, including motor vehicle accidents, trucking accidents, premises liability claims, insurance disputes, and complex injury cases. She is known for her preparation, attention to detail, and ability to guide clients through the litigation process with clarity and confidence.Zirwa understands that injured clients are often facing physical pain, emotional stress, and uncertainty about the future. Her goal is to make the legal process more understandable and less overwhelming while providing strong, strategic representation. She is committed to protecting her clients’ rights, holding responsible parties accountable, and helping each client move toward the best possible outcome.",
    category: "associates",
  },
  {
    id: "milton-hammond",
    name: "Milton Hammond",
    position: "Attorney at Law",
    image: "",
    bio: "Milton Hammond serves as an Associate Attorney in the firm’s litigation department, bringing decades of legal experience and nearly 30 years of litigation experience to his role. Since joining the firm in January 2025, Milton has handled a wide range of litigation responsibilities, including trials, mediations, depositions, written discovery, case evaluation, and client communication.\n\nMilton’s practice focuses on plaintiff’s personal injury litigation, including car accidents, medical malpractice, premises liability, and other injury-related matters. He has also handled commercial litigation and insurance defense matters, giving him a broad understanding of litigation strategy from multiple perspectives. Milton is admitted to practice in Texas state and federal courts and before the United States Supreme Court.\n\nKnown for being proactive, driven, compassionate, and client-focused, Milton values direct personal communication with clients and co-workers. He believes that strong communication is essential to helping clients feel informed and supported throughout the litigation process. When working with clients who are stressed, injured, or uncertain, Milton takes time to listen carefully, ask thoughtful questions, and offer practical guidance.\n\nMilton is motivated by the opportunity to make a positive difference in clients’ lives. He enjoys trying cases, resolving cases, and helping clients move forward. Among his professional accomplishments, Milton has helped secure significant trial results, including serving as co-counsel in a medical malpractice case that resulted in a $4 million verdict. He also successfully tried a commercial real estate commission case, obtained a verdict, and later retried and won the case again after appeal.\n\nBorn and raised in Texas, Milton grew up in Dallas and moved to Houston in 2020. Outside of work, he enjoys music, rock climbing, and camping. A unique fact about Milton is that he got married in Hawaii and previously worked in the Los Angeles office of a Dallas-based law firm.",
    category: "associates",
  },

  // STAFF
  {
    id: "agha-sikander",
    name: "Agha",
    position: "Litigation Paralegal",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "iwan-calderon",
    name: "Iwan",
    position: "Senior Litigation Paralegal",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "susan-von-sternberg",
    name: "Susan",
    position: "Senior Litigation Paralegal",
    image: "/images/headshots/susan photo .png",
    bio: "",
    category: "staff",
  },
  {
    id: "rekhan-ismail",
    name: "Rekhan",
    position: "Legal Assistant",
    image: "/images/headshots/Rekhan headshot.png",
    bio: "",
    category: "staff",
  },
  {
    id: "edwin-dominguez",
    name: "Edwin",
    position: "Legal Assistant",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "eunge-yi",
    name: "Eunge",
    position: "Senior Case Manager",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "glenda-castillo",
    name: "Glenda",
    position: "Case Manager",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "nathaly-portillo",
    name: "Nathaly",
    position: "Case Manager",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "valerie-v",
    name: "Valerie",
    position: "Case Manager",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "raven-n",
    name: "Raven",
    position: "Case Manager",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "maria-hernandez",
    name: "Maria",
    position: "Case Manager",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "sandra-rosas",
    name: "Sandra",
    position: "Case Manager",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "patricia-sierra",
    name: "Patricia",
    position: "Case Manager",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "liz-reyes",
    name: "Liz",
    position: "Intake Specialist",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "klarissa-avila",
    name: "Klarissa",
    position: "Intake Assistant",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "dahlia-gamez",
    name: "Dahlia",
    position: "Receptionist / Legal Assistant",
    image: "/images/headshots/dahlia .png",
    bio: "",
    category: "staff",
  },
  {
    id: "kathy-giron",
    name: "Kathy",
    position: "Intern – Legal Assistant",
    image: "/images/headshots/kathy .png",
    bio: "",
    category: "staff",
  },
  {
    id: "karla-rodriguez",
    name: "Karla",
    position: "Marketing Specialist",
    image: "",
    bio: "",
    category: "staff",
  },
  {
    id: "mayela-figueroa",
    name: "Mayela",
    position: "Bills and Records Clerk",
    image: "/images/headshots/meyla headshot 2.png",
    bio: "",
    category: "staff",
  },
];
